### ISSUE TITLE
I can't access to the local server with an Ajax request

### ISSUE THREAD

**Issue by AlexandreWahl** [SteeveDroz/diskuss#10]
Hi,

I'm trying to create a client using Javascript and Ajax requests.

When I do my ajax request on "localhost:8081/info/"
![code](https://cloud.githubusercontent.com/assets/22148111/18434414/43241774-78ed-11e6-9620-6faec55cb437.png)

 I got this error :
![error](https://cloud.githubusercontent.com/assets/22148111/18434226/31d3d4ec-78ec-11e6-80b3-de319172c3e0.png)

I think that the server don't accept external requests.

Alexandre Wahl

**Comment by SteeveDroz** [comment]
Support for CORS has been added.
