### ISSUE TITLE
Modifying the channel name

### ISSUE THREAD

**Issue by SaricJasmin** [SteeveDroz/diskuss#11]
Hello there, I've just seen that there is no way to rename a channel, I want to ask if there'll be a possibility to do that in the futur.
I'm saying that because there could be some cases where modifying the name of a channel is way easier than deleting an older channel and creating a new one.
(e.g. Someone has a large number of channels, he wants to change the name of all of his channels but there are people connected in some of those channels or he wants to keep the description of his channel, he could just rename it and it'll keep the description despite of copying the description, creating a new channel...)

**Comment by SteeveDroz** [comment]
That would imply that someone can force people into channels. If there are people in, say, the channel `#help`, the owner could change its name to `#i-like-poneys`, forcing all the people in `#help` to be part of some channel they may not want to go to.

I think the best way would be to implement that in your client, "renaming" a channel would mean copy its content and sending an invitation to join the other channel to everyone in the current channel. Something like

    * This channel is closing, follow the discussion in #i-like-poneys.

**Comment by SaricJasmin** [comment]
I don't know if it's really the best, if people just rename channels to put the users angry, that's not cool and I agree. If there's a registery function that'll be much more controlled.
In other hand, I'm an officer in a TeamSpeak 3 server ("Controlling the crowd"(if someone does some real bad things, you know the consequences, or I'm just sitting here if someone needs help) and talking to the moderators for some ideas), and I saw some channels with sub-channels, and I did create with a moderator a bunch of sub-channels, and I might not think what would happen if we couldn't rename the channels...
("Hey, the main channel containing x sub-channels containing y sub-channels each has got a wrong name!" "Huh?...").

**Comment by SteeveDroz** [comment]
As there won't be any subchannel, I don't see the point of doing that. Names are channel IDs, changing a name means changing the ID. It's too complicated to do so and Diskuss wasn't created for that.

Thanks anyway for the idea, I'll keep it in mind for Diskuss v2.0!
