### ISSUE TITLE
Create a channel

### ISSUE THREAD

**Issue by becaudar** [SteeveDroz/diskuss#15]
Hi!
Is it possible to create a channel ? I've been looking in the Diskuss API page that shows the comprehensive list of request that are included and I didn't found this possibility.
Thank you.

**Comment by SteeveDroz** [comment]
Hello, thanks for your interrest.

There are no commands to "create" a channel, but joining one that doesn't exists first creates it. So the first user who uses the `join` command on a channel that doesn't exist creates it and gets the "owner" status for it.

Likewise, when all the users leave a channel, it is destroyed (except if the owner used the `keep` command).
