### ISSUE TITLE
Objet vs Tableau

### ISSUE THREAD

**Issue by greut** [SteeveDroz/diskuss#3]
Les fonctions `findUser` et `findChannel` sont un peu ringardes. Si tu persistes à vouloir conserver des tableaux, utilise la méthode `find` pour tes recherches, sinon, un objet (tableau associatif) me paraitrait faire complétement l'affaire.

`findChannel` semble faire un peu plus que juste `find`. Un des idiômes de Python est que si une fonction retourne quelque chose, elle ne modifie rien. Si elle modifie quelque chose, alors elle ne retournera rien.

```python
>>> a = [3,2,1]
>>> sorted(a)
[1, 2, 3]
>>> a
[3, 2, 1]
>>> a.sort()
>>> a
[1, 2, 3]
```

**Comment by SteeveDroz** [comment]
C'est bon pour `findUser` et `findUsersInChannel`, mais est-ce que cet idiome est compatible avec le design pattern "lazy initialization" (create if not found) ? Il me semble difficile de mettre ça en place en tenant compte de cette convention.

**Comment by greut** [comment]
Ce “design pattern” est laid car `findUser` ne t'offre aucune information quant à ce qui se passe si rien n'est trouvé. Intuitivement, j'imaginerais obtenir une exception ou, au pire, la valeur `null`. `findOrCreateUser` serait certainement un meilleur nom.

Dans tous les cas, faire une recherche à l'aide d'une boucle `for` n'est pas très moderne.

Sans parler du fait que `users` et `channels` sont des variables globales ;-)

**Comment by SteeveDroz** [comment]
J'adore/je déteste bosser avec toi. Je me rends compte que je n'y connais rien au Javascript après tout... J'ai appris en autodidacte il y a 15 ans ! ![XKCD code quality](http://imgs.xkcd.com/comics/code_quality.png)

**Comment by SteeveDroz** [comment]
Terminé ! (j'espère)
