### ISSUE TITLE
Discussion impossible

### ISSUE THREAD

**Issue by SteeveDroz** [SteeveDroz/diskuss#5]
La ligne https://github.com/SteeveDroz/diskuss/blob/dev/server.js#L228 fonctionnait avant les modifications de @greut mais `req.body` est nul depuis.

Une idée ?

**Comment by greut** [comment]
Si seulement c'était de ma faute... http://stackoverflow.com/a/27855234/122978

`superagent` peut te permettre de tester tes contrôleurs.

**Comment by SteeveDroz** [comment]
:dizzy_face: Extra, merci du coup de main !
